#!/usr/bin/env bash
# Ran after `npm run dist`. Builds `releases/` which will be automatically
# deployed to GitHub.

VERSION=$(node -e 'console.log(require("./package.json").version)')

rm -rf release
mkdir release

cd dist/Halla-osx-x64
echo "Building halla-osx.zip..."
zip -9rq ../../release/halla-osx.zip *
cd -

# cd dist/Halla-win-x64
# echo "Building halla-win.zip..."
# zip -9rq ../../release/halla-win.zip *
# cd -

# cd dist/Halla-linux-x64
# echo "Building halla-linux.tar.gz..."
# tar cf ../../release/halla-linux.tar.gz *
# cd -

echo ""
find release
