#!/usr/bin/env bash
# Ran after `npm run dist`. Builds `releases/` which will be automatically
# deployed to GitHub.

VERSION=$(node -e 'console.log(require("./package.json").version)')

rm -rf release
mkdir release

cd dist/Halla-osx-x64
echo "Building halla-osx.zip..."
zip -9rq ../../release/halla-osx.zip *.app credits.html
cd -

echo ""
find release
