#!/usr/bin/env bash
REPO=rstacruz/halla
VERSION=$(node -e 'console.log(require("./package.json").version)')

curl \
  -XPOST \
  -H "Authorization:token $GITHUB_TOKEN" \
  -H "Content-Type:application/octet-stream" \
  --data-binary @yourbinary.exe \
  https://uploads.github.com/repos/${REPO}/releases/${VERSION}/assets?name=yourbinary.exe
