#!/usr/bin/env bash
VERSION=$(node -e 'console.log(require("./package.json").version)')

if ! which github-release 2>&1 >/dev/null; then
  echo "You need github-release"
  echo "See: https://github.com/aktau/github-release"
  exit 1
fi

echo "* Creating GitHub release..."
github-release release \
  --user rstacruz \
  --repo halla \
  --tag "v${VERSION}" \
  --name "v${VERSION}"

echo "* Uploading artifacts:"
for fn in release/*; do
  echo "  $fn..."
  github-release upload \
    --user rstacruz \
    --repo halla \
    --tag "v${VERSION}" \
    --name $(basename $(echo $fn)) \
    --file "$fn"
done
